# Generated by Django 5.1.4 on 2025-03-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in hours'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_worker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='services.user'),
        ),
    ]
