# Generated by Django 5.1.4 on 2025-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_booking_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
