# Generated by Django 5.1.4 on 2025-03-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_workerprofile_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.ForeignKey(default=False, limit_choices_to={'is_worker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.workerprofile'),
        ),
    ]
