# Generated by Django 5.1.4 on 2025-03-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_booking_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
